### ISSUE TITLE
JWT 로그인할 때 로그인한 사용자 정보 반환하기

### ISSUE THREAD

**Issue by litsynp** [Valley-Zoomindle/backend_handshakers#1]
클라이언트에서 JWT 로그인시 token 정보만이 아니라 사용자 정보도 같이 반환하여 사용자 정보 (및 회사 정보)를 알 수 있어야 함.

![image](https://user-images.githubusercontent.com/42485462/104461368-9a0e3100-55f2-11eb-8339-fc2c611940aa.png)

이런 식으로 하면 될 것 같다.
```json
{
    "token": "XXX.XXXX.XXXX",
    "user": {
        "id": 1,
        "username": "thinkanddoit",
        "email": "thinkanddoit@gmail.com",
        "company_name": "Samsung"
    }
}
```

**Comment by sheee7** [comment]
LGTM

**Comment by litsynp** [comment]
Resolved in 2ee003cca5f435255186b8d98bbbe81e3282b588.
